### ISSUE TITLE
Search not working 

### ISSUE THREAD

**Issue by mikemike396** [klinker24/Android-GiphySearch#10]
The search doesn't seem to be working on the latest version. Even the demo app doesn't change when searching. 

        new Giphy.Builder(this, "xxxx")
                .setPreviewSize(Giphy.PREVIEW_MEDIUM)
                .maxFileSize(8 * 1024 * 1024)
                .start();

![screenshot_1548815431](https://user-images.githubusercontent.com/14999806/51954187-3bebe180-240d-11e9-9cba-04ff3a74574d.png)

**Comment by mikemike396** [comment]
Seems like it works if I click the search button on the keyboard, but pressing return on my emulator was not working.

**Comment by klinker24** [comment]
The library does not listen for "return" key events, since the Android keyboard displays the search button. This is not relevant for using the library in an actual app.
