### ISSUE TITLE
how to show selected gif into imageview?

### ISSUE THREAD

**Issue by Aksh0377** [klinker24/Android-GiphySearch#6]

**Comment by klinker24** [comment]
The sample app does this. https://github.com/klinker24/Android-GiphySearch/blob/master/example/src/main/java/xyz/klinker/giphy_example/MainActivity.java#L78

If you don't want to manage showing them yourself, you could use `Glide`, which handles GIFs on it's own.

**Comment by Aksh0377** [comment]
Thanks for quick response and help; it solved the problem. :)
