### ISSUE TITLE
Unable to implement library?

### ISSUE THREAD

**Issue by uzaysan** [klinker24/Android-GiphySearch#9]
```
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:13:5-62:19 to override.
```

When i tried to implement your library via gradle it give me error. Any idea?

one more question.Does this library returns selected gifs url or download gif to phone?

**Comment by klinker24** [comment]
Looks like you have not updated your app to use Android x. You will have to download a previous version of the library. Anything below 2.0.

https://github.com/klinker24/Android-GiphySearch/blob/master/changelog.md

It saves them to your phone and provides the uri.

**Comment by uzaysan** [comment]
So is there any way to just get gif url.I dont wanna save it.

**Comment by klinker24** [comment]
You would have to customize the library yourself, to do this. The library doesn't provide it.
